import {clone,exactKeys,hash,instant,noSecrets,report,requireThat,text} from './common.js';
// Pure release preparation. No network, deployment, credentials, authority switch or legacy reads.
export async function buildReleaseLock({release_id,created_at,expires_at,components,legacy_final_declared=false}){
 text(release_id,'RELEASE_ID');const start=instant(created_at,'RELEASE_CREATED'),end=instant(expires_at,'RELEASE_EXPIRES');requireThat(start<end,'RELEASE_INTERVAL_INVALID');requireThat(Array.isArray(components)&&components.length>0&&components.length<=50,'RELEASE_COMPONENTS_REQUIRED');const seen=new Set();
 for(const c of components){exactKeys(c,['id','repository','branch','commit_sha','kind','contract_hash'],'RELEASE_COMPONENT');text(c.id,'COMPONENT_ID');requireThat(!seen.has(c.id),'RELEASE_DUPLICATE_COMPONENT');seen.add(c.id);requireThat(/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(c.repository),'RELEASE_REPOSITORY_INVALID');text(c.branch,'RELEASE_BRANCH');requireThat(/^[a-f0-9]{40}$/.test(c.commit_sha),'RELEASE_SHA_REQUIRED');requireThat(['CODE','DATA'].includes(c.kind),'RELEASE_COMPONENT_KIND_INVALID');requireThat(/^[a-f0-9]{64}$/.test(c.contract_hash),'RELEASE_CONTRACT_HASH_REQUIRED');}
 const content={version:'openpq-release-lock-v1',release_id,created_at,expires_at,components:clone(components).sort((a,b)=>a.id.localeCompare(b.id)),legacy_final_declared:legacy_final_declared===true,assurance:'RECORDED_INPUTS_ONLY_NOT_DEPLOYMENT_PROOF',production_enabled:false};noSecrets(content);return {...content,lock_hash:await hash(content)};
}
export async function checkReleaseLock(lock,current,evaluation_time){
 const {lock_hash,...content}=lock;requireThat(await hash(content)===lock_hash,'RELEASE_LOCK_TAMPERED');const rebuilt=await buildReleaseLock(content);requireThat(rebuilt.lock_hash===lock_hash,'RELEASE_LOCK_CONTRACT_INVALID');const now=instant(evaluation_time,'RELEASE_EVALUATION'),blocked=[];
 if(now<instant(lock.created_at,'RELEASE_CREATED')||now>=instant(lock.expires_at,'RELEASE_EXPIRES'))blocked.push('RELEASE_LOCK_NOT_EFFECTIVE');if(!lock.legacy_final_declared)blocked.push('LEGACY_FINAL_RELEASE_NOT_DECLARED');requireThat(Array.isArray(current),'RELEASE_CURRENT_INVENTORY_REQUIRED');const seen=new Set();for(const c of current){requireThat(c&&typeof c.id==='string'&&!seen.has(c.id),'RELEASE_CURRENT_DUPLICATE_OR_INVALID');seen.add(c.id);}
 const drift=lock.components.map(c=>{const observed=current.find(x=>x.id===c.id);let reason=null;if(!observed)reason='CURRENT_COMPONENT_NOT_OBSERVED';else if(observed.repository!==c.repository||observed.branch!==c.branch||observed.kind!==c.kind)reason='COMPONENT_ROUTE_CHANGED';else if(observed.contract_hash!==c.contract_hash)reason='CONTRACT_CHANGED_REVIEW_REQUIRED';else if(!/^[a-f0-9]{40}$/.test(observed.commit_sha||''))reason='CURRENT_SHA_UNKNOWN';else if(c.kind==='CODE'&&observed.commit_sha!==c.commit_sha)reason='CODE_CHANGED_REINVENTORY_REQUIRED';return {id:c.id,reason,data_sha_changed:!reason&&c.kind==='DATA'&&observed.commit_sha!==c.commit_sha};});blocked.push(...drift.filter(x=>x.reason).map(x=>x.id+':'+x.reason));
 return report(blocked.length?'RELEASE_PREPARATION_BLOCKED':'RELEASE_LOCK_MATCH_INPUTS_ONLY',{lock_hash,blocked,drift,execution_allowed:false,deployments_stopped_proven:false,source_contracts_runtime_verified:false,required_next_step:'Owner announces final legacy releases, then fresh read-only inventory and actual compatibility/shadow/restore gates before cutover.'});
}
