import test from 'node:test';import assert from 'node:assert/strict';import {Miniflare} from 'miniflare';import {fileURLToPath} from 'node:url';
import {preparationFixture,SCOPE} from '../src/fixtures/preparation.js';import {hash} from '../src/platform/contracts.js';
async function setup(window_ms=60000){const f=await preparationFixture(),now=Date.now();for(const p of f.policy_inputs)if(p.status==='APPROVED_RECORDED'){p.effective_from=new Date(now-60000).toISOString();p.effective_to=new Date(now+3600000).toISOString();}const p=f.policy_inputs.find(p=>p.policy_id==='P10');Object.assign(p.values,{request_window_ms:window_ms,timeout_ms:1000,lease_ms:2000});const config={environment_id:'local-test',enabled:true,dataset_id:SCOPE,policies:f.policy_inputs};let status=200,calls=0;
 const bindings={ENVIRONMENT_ID:'local-test',PROGRESS_CONFIG_JSON:JSON.stringify(config),PROGRESS_CONFIG_HASH:await hash(config),SCHEDULER_TOKEN_HASH:await hash('local-only-scheduler'),EXPORT_ONLY_TOKEN:'local-only-export'};
 const options={cf:false,host:'127.0.0.1',workers:[{name:'progress',modules:true,scriptPath:fileURLToPath(new URL('../src/workers/progress.js',import.meta.url)),modulesRules:[{type:'ESModule',include:['**/*.js']}],compatibilityDate:'2026-07-30',durableObjects:{PROGRESS:{className:'ProgressScheduler',useSQLite:true}},bindings,serviceBindings:{CORE_EXPORT:async request=>{assert.equal(new URL(request.url).pathname,'/datasets/'+SCOPE+'/export');assert.equal(request.method,'POST');assert.equal(request.headers.get('authorization'),'Bearer local-only-export');calls++;return Response.json({exported:[1]},{status});}}}]};const mf=new Miniflare(options);const call=async(path,body,token='local-only-scheduler')=>{const w=await mf.getWorker('progress');const r=await w.fetch('https://progress'+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json()};};return {mf,call,options,bindings,setStatus:s=>status=s,calls:()=>calls};}
const job=id=>({id,kind:'EXPORT_CHECKPOINT',dataset_id:SCOPE,expires_at:new Date(Date.now()+3600000).toISOString()});
test('native SQLite progress Worker admits only authenticated scoped export jobs and deduplicates after eviction',async()=>{const x=await setup();try{const j=job('one');assert.equal((await x.call('/enqueue',j,'wrong')).status,401);assert.equal((await x.call('/enqueue',{...j,kind:'PROMOTE'})).body.error,'PROGRESS_TASK_DENIED');assert.equal((await x.call('/enqueue',j)).body.created,true);assert.equal((await x.call('/enqueue',j)).body.created,false);assert.equal((await x.call('/tick',{})).body.results[0].state,'DONE');assert.equal(x.calls(),1);const ns=await x.mf.getDurableObjectNamespace('PROGRESS','progress');await x.mf.unsafeEvictDurableObject('progress','ProgressScheduler',{id:ns.idFromName('local-test/progress').toString()});assert.equal((await x.call('/enqueue',j)).body.created,false);assert.equal((await x.call('/status')).body.jobs[0].state,'DONE');assert.ok((await x.call('/status')).body.alarm_at);}finally{await x.mf.dispose();}});
test('native export retry stays pending on 503 but permission denial quarantines and config mutation cannot reuse queue',async()=>{const x=await setup();try{x.setStatus(503);await x.call('/enqueue',job('retry'));assert.equal((await x.call('/tick',{})).body.results[0].state,'PENDING');x.setStatus(401);await x.call('/enqueue',job('denied'));const report=await x.call('/tick',{});assert.equal(report.body.results.find(r=>r.id==='denied').state,'QUARANTINED');const config=JSON.parse(x.bindings.PROGRESS_CONFIG_JSON);config.policies.find(p=>p.policy_id==='P10').values.requests=5;x.options.workers[0].bindings={...x.bindings,PROGRESS_CONFIG_JSON:JSON.stringify(config),PROGRESS_CONFIG_HASH:await hash(config)};await x.mf.setOptions(x.options);assert.equal((await x.call('/status')).body.error,'PROGRESS_POLICY_MIGRATION_REQUIRED');}finally{await x.mf.dispose();}});
test('native progress Worker refuses isolated/production activation even when a local test token is known',async()=>{const x=await setup();try{x.options.workers[0].bindings={...x.bindings,ENVIRONMENT_ID:'isolated-test'};await x.mf.setOptions(x.options);assert.equal((await x.call('/status')).body.error,'PROGRESS_CLOUD_ACTIVATION_CLOSED');x.options.workers[0].bindings={...x.bindings,ENVIRONMENT_ID:'production'};await x.mf.setOptions(x.options);assert.equal((await x.call('/status')).status,503);assert.equal(x.calls(),0);}finally{await x.mf.dispose();}});

test('native alarm actually exports the pending checkpoint without a manual tick',async()=>{const x=await setup(100);try{await x.call('/enqueue',job('alarm'));const until=Date.now()+3000;let state;while(Date.now()<until){state=(await x.call('/status')).body.jobs[0].state;if(state==='DONE')break;await new Promise(resolve=>setTimeout(resolve,20));}assert.equal(state,'DONE');assert.equal(x.calls(),1);}finally{await x.mf.dispose();}});
