import test from 'node:test';import assert from 'node:assert/strict';import {Miniflare} from 'miniflare';import {fileURLToPath} from 'node:url';
import {progressFixtureConfig,validateProgressScope} from '../src/preparation/progress-config.js';import {hash} from '../src/platform/contracts.js';
const account='a'.repeat(32),dataset='fixture.progress.native',now=()=>new Date().toISOString();
test('isolated fixture config is time/account/scope pinned and cannot activate a real dataset or production',async()=>{
 const {config:c}=await progressFixtureConfig(account,dataset,now());validateProgressScope(c,'isolated-test',account,now());
 for(const patch of [{fixture_only:false},{dataset_id:'marine.real'},{account_id:'b'.repeat(32)},{valid_until:'2020-01-01T00:00:00Z'},{cloud_activation:'LIVE'}])assert.throws(()=>validateProgressScope({...c,...patch},'isolated-test',account,now()),/PROGRESS_CLOUD_ACTIVATION_CLOSED|PROGRESS_FIXTURE_EXPIRED/);
 assert.throws(()=>validateProgressScope({...c,environment_id:'production'},'production',account,now()),/PROGRESS_CLOUD_ACTIVATION_CLOSED/);
});
test('native isolated alarm uses export-only binding, retains idempotency and closes when capability disappears',async()=>{
 const f=await progressFixtureConfig(account,dataset,now());let calls=0;
 const bindings={ENVIRONMENT_ID:'isolated-test',TEST_ACCOUNT_ID:account,PROGRESS_CONFIG_JSON:JSON.stringify(f.config),PROGRESS_CONFIG_HASH:f.config_hash,SCHEDULER_TOKEN_HASH:await hash('synthetic-test-scheduler'),EXPORT_ONLY_TOKEN:'synthetic-test-export'};
 const options={cf:false,workers:[{name:'progress',modules:true,scriptPath:fileURLToPath(new URL('../src/workers/progress.js',import.meta.url)),modulesRules:[{type:'ESModule',include:['**/*.js']}],compatibilityDate:'2026-07-30',durableObjects:{PROGRESS:{className:'ProgressScheduler',useSQLite:true}},bindings,serviceBindings:{CORE_EXPORT:async request=>{assert.equal(new URL(request.url).pathname,'/datasets/'+dataset+'/export');assert.equal(request.headers.get('authorization'),'Bearer synthetic-test-export');calls++;return Response.json({exported:[1]});}}}]};
 const mf=new Miniflare(options);const call=async(path,body)=>{const w=await mf.getWorker('progress');const r=await w.fetch('https://progress'+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer synthetic-test-scheduler','content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json()};};
 try{const job={id:'native-cloud-fixture',kind:'EXPORT_CHECKPOINT',dataset_id:dataset,expires_at:new Date(Date.now()+60000).toISOString()};assert.equal((await call('/enqueue',job)).body.created,true);const end=Date.now()+5000;let state;while(Date.now()<end){state=(await call('/status')).body.jobs[0]?.state;if(state==='DONE')break;await new Promise(r=>setTimeout(r,30));}assert.equal(state,'DONE');assert.equal(calls,1);assert.equal((await call('/enqueue',job)).body.created,false);assert.equal((await call('/status')).body.cloud_activation,true);options.workers[0].bindings={...bindings,SCHEDULER_TOKEN_HASH:'',EXPORT_ONLY_TOKEN:''};await mf.setOptions(options);assert.equal((await call('/status')).body.error,'PROGRESS_CAPABILITY_MISSING');assert.equal(calls,1);}finally{await mf.dispose();}
});
