import test from 'node:test';import assert from 'node:assert/strict';
import {setup,iso} from './support.js';import {preparationFixture} from '../src/fixtures/preparation.js';
import {hash,stable} from '../src/platform/contracts.js';import {buildSemanticCandidate,packAdmissionProfile,validateSemanticAdmission} from '../src/platform/semantic-admission.js';
import {servingView} from '../src/platform/serving.js';
const copy=x=>JSON.parse(JSON.stringify(x));
async function fixture({faults=false,age_ms=3600000,validity_ms=3600000}={}){
 const now=Date.now(),at=iso(now);const f=await preparationFixture({P05:{values:{max_source_age_ms:age_ms,clock_skew_ms:0}}},'cano.operation',at);
 for(const e of f.evidences){e.source_time=iso(now-100);e.collected_at=iso(now-50);e.received_at=iso(now-10);e.source_validity={valid_from:iso(now-100),valid_to:iso(now+3600000)};}
 for(const a of f.assertions){a.source_time=f.evidences[0].source_time;a.issued_at=a.source_time;a.valid_from=a.source_time;a.valid_to=iso(now+3600000);}
 const profile={contract_version:'openpq-semantic-admission-local-v1',environment_id:'local-test',dataset_id:'cano.operation',source_kind:'SYNTHETIC_ONLY',artifacts:f.artifacts,policies:f.policy_inputs,artifact_refs:f.artifact_refs,target_scope:f.target_scope};
 const s=await setup({faults,semanticProfile:profile});const current=Date.now(),evaluation=iso(current);for(const e of f.evidences){e.source_time=iso(current-100);e.collected_at=iso(current-50);e.received_at=iso(current-10);e.source_validity={valid_from:iso(current-100),valid_to:iso(current+validity_ms)};}for(const a of f.assertions){a.source_time=f.evidences[0].source_time;a.issued_at=a.source_time;a.valid_from=a.source_time;a.valid_to=iso(current+validity_ms);}
 const c=await buildSemanticCandidate(profile,s.trust,{evidences:f.evidences,assertions:f.assertions,evaluation_time:evaluation,candidate_id:'semantic-one',logical_slot:10});return {s,c,f,profile};
}
test('trusted semantic facts traverse actual Coordinator, immutable blob, receipt and Runtime without action eligibility',async()=>{const {s,c}=await fixture();try{const p=await s.call('prepare',c);assert.equal(p.status,200);const result=await s.commit(p.body,'semantic-commit');assert.equal(result.status,200);assert.equal(result.body.receipt.semantic_admission.profile_hash,s.trust.semantic_profile_hash);const r=await s.runtime.fetch('https://runtime/datasets/cano.operation');assert.equal(r.status,200);const body=await r.json();assert.equal(body.data.semantic_fact.values[0].value,true);assert.equal(body.decision.effect,'ABSTAIN');assert.equal(body.serving.decision_eligibility,'ABSTAIN');assert.equal(body.serving.authority,'VERIFIED');assert.equal((await s.call('export',{},'test-only-operator')).status,200);const repeat=await s.commit(p.body,'semantic-commit');assert.deepEqual(repeat.body.receipt,result.body.receipt);}finally{await s.mf.dispose();}});
test('configured semantic dataset cannot bypass admission using a generic candidate or producer-supplied forged payload',async()=>{const {s,c}=await fixture();try{const bucket=await s.mf.getR2Bucket('CANONICAL','core');for(const change of [x=>{delete x.semantic_bundle;delete x.semantic_admission;},x=>x.payload.semantic_fact.values[0].value=false,x=>x.inputs[0].max_age_ms*=2,x=>x.artifacts.rule='f'.repeat(64),x=>x.decision.effect='POSITIVE',x=>x.semantic_admission.profile_hash='f'.repeat(64),x=>x.semantic_profile_hash='f'.repeat(64),x=>x.valid_to=iso(Date.parse(x.valid_to)+1000)]){const bad=copy(c);change(bad);const r=await s.call('prepare',bad);assert.notEqual(r.status,200);assert.equal((await s.call('read',undefined,'test-only-read')).body.state.revision,0);}assert.equal((await bucket.list({prefix:'generations/'})).objects.length,0);}finally{await s.mf.dispose();}});
test('semantic profile packaging respects UTF-8 binding limits and pins exact content; unactivated/isolated paths fail closed',async()=>{const {s,c,profile}=await fixture();try{const bindings=await packAdmissionProfile(profile);assert.ok(Object.values(bindings).every(p=>new TextEncoder().encode(p).length<=5000));await assert.rejects(validateSemanticAdmission({ENVIRONMENT_ID:'local-test',...bindings},{...s.trust,semantic_profile_hash:'f'.repeat(64)},c,iso(Date.now())),/PROFILE_PIN_MISMATCH/);await assert.rejects(validateSemanticAdmission({ENVIRONMENT_ID:'isolated-test',...bindings},s.trust,c,iso(Date.now())),/CLOUD_ADMISSION_CLOSED/);const {semantic_profile_hash,...genericTrust}=s.trust;await assert.rejects(validateSemanticAdmission({ENVIRONMENT_ID:'local-test'},genericTrust,c,iso(Date.now())),/NOT_ACTIVATED/);await assert.rejects(packAdmissionProfile({...profile,note:'x'.repeat(16000)}),/TOO_LARGE/);}finally{await s.mf.dispose();}});
test('commit rejects actual source expiry after prepare, while refetch cannot renew source age',async()=>{const {s,c,profile}=await fixture({validity_ms:1500});try{const p=await s.call('prepare',c);assert.equal(p.status,200);const store=await s.mf.getR2Bucket('CANONICAL','core');assert.ok(await store.get(p.body.key));
 const expired=copy(c);expired.semantic_bundle.evidences[0].source_time=iso(Date.now()-7200000);expired.semantic_bundle.assertions[0].source_time=expired.semantic_bundle.evidences[0].source_time;expired.semantic_bundle.evidences[0].collected_at=iso(Date.now());expired.semantic_bundle.evidences[0].received_at=iso(Date.now());await assert.rejects(validateSemanticAdmission({ENVIRONMENT_ID:'local-test',...await packAdmissionProfile(profile)},s.trust,expired,iso(Date.now())),/INPUT_NOT_ADMISSIBLE|OUTPUT_MISMATCH/);
 const wait=Math.max(0,Date.parse(c.valid_to)-Date.now()+30);assert.ok(wait<2000);await new Promise(resolve=>setTimeout(resolve,wait));const denied=await s.commit(p.body,'expired-commit');assert.notEqual(denied.status,200);assert.equal(denied.body.error,'SEMANTIC_SOURCE_STALE_AT_ADMISSION');assert.equal((await s.call('read',undefined,'test-only-read')).body.state.revision,0);assert.ok(await store.get(p.body.key));
 }finally{await s.mf.dispose();}});
test('semantic profile and content-bound idempotency survive actual Coordinator eviction',async()=>{const {s,c}=await fixture();try{const p=await s.call('prepare',c);const committed=await s.commit(p.body,'eviction-repeat');assert.equal(committed.status,200);await s.mf.unsafeEvictDurableObject('core','DatasetCoordinator',{id:s.trust.native_id});assert.deepEqual((await s.commit(p.body,'eviction-repeat')).body.receipt,committed.body.receipt);}finally{await s.mf.dispose();}});
test('semantic profile change is an activation migration, not a normal binding edit; Runtime rejects old-profile serving',async()=>{const {s,c}=await fixture();try{const p=await s.call('prepare',c);const result=await s.commit(p.body,'one');assert.equal(result.status,200);const changed={...s.trust,semantic_profile_hash:'f'.repeat(64)};assert.throws(()=>servingView(c,result.body.receipt,changed,null,Date.now()),/SEMANTIC_SERVING_PROFILE_DENIED/);const opts=s.options();opts.workers[0].bindings.TRUST_JSON=JSON.stringify({'cano.operation':changed});await s.mf.setOptions(opts);const r=await s.call('read',undefined,'test-only-read');assert.equal(r.body.error,'CONTROL_SEMANTIC_PROFILE_MISMATCH');}finally{await s.mf.dispose();}});
test('semantic publication connects to actual export-only alarm and signed Runtime fallback across the complete local stack',async()=>{
 const at=iso(Date.now()),budget={requests:4,concurrency:2,retries:2,payload_bytes:1024,timeout_ms:1000,queue_limit:4,lease_ms:2000,retry_base_ms:10,retry_max_ms:40,request_window_ms:100};const f=await preparationFixture({P10:{values:budget}},'cano.operation',at),profile={contract_version:'openpq-semantic-admission-local-v1',environment_id:'local-test',dataset_id:'cano.operation',source_kind:'SYNTHETIC_ONLY',artifacts:f.artifacts,policies:f.policy_inputs,artifact_refs:f.artifact_refs,target_scope:f.target_scope},progressConfig={enabled:true,environment_id:'local-test',dataset_id:'cano.operation',policies:f.policy_inputs};
 const s=await setup({semanticProfile:profile,progressConfig});try{const now=Date.now();for(const e of f.evidences){e.source_time=iso(now-100);e.collected_at=iso(now-50);e.received_at=iso(now-10);e.source_validity={valid_from:iso(now-100),valid_to:iso(now+60000)};}for(const a of f.assertions){a.source_time=f.evidences[0].source_time;a.issued_at=a.source_time;a.valid_from=a.source_time;a.valid_to=iso(now+60000);}
 const c=await buildSemanticCandidate(profile,s.trust,{evidences:f.evidences,assertions:f.assertions,evaluation_time:iso(now),candidate_id:'alarm-semantic',logical_slot:10}),p=await s.call('prepare',c),committed=await s.commit(p.body,'alarm-publication');assert.equal(committed.status,200);
 assert.equal((await s.call('prepare',c,'test-only-export')).status,403);assert.equal((await s.call('control',{action:'FREEZE'},'test-only-export')).status,403);
 const progress=await s.mf.getWorker('progress');const queued=await progress.fetch('https://progress/enqueue',{method:'POST',headers:{authorization:'Bearer test-only-scheduler','content-type':'application/json'},body:JSON.stringify({id:'alarm-export',kind:'EXPORT_CHECKPOINT',dataset_id:'cano.operation',expires_at:iso(now+60000)})});assert.equal(queued.status,200);
 const deadline=Date.now()+4000;let state;while(Date.now()<deadline){const r=await progress.fetch('https://progress/status',{headers:{authorization:'Bearer test-only-scheduler'}});state=(await r.json()).jobs[0].state;if(state==='DONE')break;await new Promise(resolve=>setTimeout(resolve,20));}assert.equal(state,'DONE');
 const b=await s.mf.getR2Bucket('CANONICAL','core'),checkpoint=await b.get(`checkpoints/${s.trust.authority_instance_id}/${s.trust.recovery_generation}/latest.json`);assert.ok(checkpoint);
 const capturedEnvelope=JSON.parse(await checkpoint.text()),capturedGeneration=JSON.parse(await (await b.get(capturedEnvelope.receipt.key)).text()),capturedControl=(await s.call('read',undefined,'test-only-read')).body.state;
 assert.equal(capturedEnvelope.receipt.semantic_admission.profile_hash,s.trust.semantic_profile_hash);
 const actor=s.principals.find(p=>p.id==='read');actor.permissions=[];await s.mf.setOptions(s.options());const runtime=await s.mf.getWorker('runtime'),r=await runtime.fetch('https://runtime/datasets/cano.operation');assert.equal(r.status,200);const body=await r.json();assert.equal(body.serving.fallback,true);assert.equal(body.serving.authority,'UNVERIFIED');assert.equal(body.serving.decision_eligibility,'ABSTAIN');assert.equal(body.data.semantic_fact.operational_action_allowed,false);
 const {buildBackup}=await import('../src/preparation/recovery.js'),{verifyBackupPublications}=await import('../src/preparation/backup-authenticity.js');const envelope=capturedEnvelope,generation=capturedGeneration,control=capturedControl;const backup=await buildBackup({environment_id:'local-test',authority:s.trust,created_at:iso(Date.now()),watermark:{revision:control.revision,control_revision:control.control_revision},required_keys:['control',envelope.receipt.key,'receipt'],records:[{key:'control',kind:'CONTROL',content:control},{key:envelope.receipt.key,kind:'GENERATION',content:generation},{key:'receipt',kind:'RECEIPT',content:envelope},...['AUDIT','REGISTRY','SCHEDULER','DEPLOY'].map(kind=>({key:kind.toLowerCase(),kind,content:kind==='REGISTRY'?{artifacts:profile.artifacts}:{synthetic_fixture:true}}))]});const authenticated=await verifyBackupPublications(backup,s.trust);assert.equal(authenticated.publication_receipt_authenticity_verified,true);assert.equal(authenticated.control_authenticity_verified,false);assert.equal(authenticated.resume_writer,false);await assert.rejects(verifyBackupPublications(backup),/INDEPENDENT_TRUST_REQUIRED/);const tampered=copy(envelope);tampered.receipt.revision=2;const bad=await buildBackup({...backup,records:backup.entries.map(e=>({key:e.key,kind:e.kind,content:e.kind==='RECEIPT'?tampered:e.content}))});await assert.rejects(verifyBackupPublications(bad,s.trust),/CHECKPOINT_SIGNATURE_INVALID/);
 }finally{await s.mf.dispose();}
});

test('future assertion issue time, nested credentials and incomplete source linkage cannot enter semantic storage',async()=>{const {s,c}=await fixture();try{for(const change of [x=>x.semantic_bundle.assertions[0].issued_at=iso(Date.now()+3600000),x=>x.semantic_bundle.evidences[0].token='not-a-real-credential',x=>x.semantic_bundle.evidences.push({...x.semantic_bundle.evidences[0],evidence_id:'unused'})]){const bad=copy(c);change(bad);assert.notEqual((await s.call('prepare',bad)).status,200);}const b=await s.mf.getR2Bucket('CANONICAL','core');assert.equal((await b.list({prefix:'generations/'})).objects.length,0);}finally{await s.mf.dispose();}});

test('a control command ID and digest cannot be replayed as a publication receipt',async()=>{const {s}=await fixture();try{const body={command_id:'control-only',expected_control_revision:0,expires_at:iso(Date.now()+60000),action:'FREEZE',frozen:true,reason:'Synthetic protection'};assert.equal((await s.call('control',body,'test-only-operator')).status,200);const forged=await s.call('commit',{...s.trust,command_id:body.command_id,digest:await hash(body),expires_at:iso(Date.now()+60000)});assert.equal(forged.body.error,'COMMAND_KIND_CONFLICT');assert.equal((await s.call('read',undefined,'test-only-read')).body.state.revision,0);}finally{await s.mf.dispose();}});
