import { ContractError, requireThat } from '../platform/contracts.js';

// This console is separate from JoTrip Ops. It forwards the operator's own capability,
// never a shared superuser credential. Tokens stay in page memory only.
const page=`<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OpenPQ Operator Console</title><link rel="stylesheet" href="/style.css"><main><h1>OpenPQ Operator Console</h1><p>Môi trường test riêng. Không kết nối JoTrip Ops.</p><label>Dataset <input id="dataset" value="cano.operation"></label><label>Capability token <input id="token" type="password" autocomplete="off"></label><button id="read">Đọc trạng thái</button><label>Lệnh <select id="action"><option>FREEZE</option><option>TRANSFER</option><option>RESTRICT_AT</option></select></label><label>Giá trị (true/false, owner hoặc UTC effective_from) <input id="value"></label><label>Lý do <input id="reason" maxlength="256"></label><button id="command">Gửi lệnh</button><pre id="result" role="status" aria-live="polite">Chưa đọc trạng thái.</pre></main><script src="/console.js"></script></html>`;
const script=`let state=null;const el=id=>document.getElementById(id);const show=x=>el('result').textContent=JSON.stringify(x,null,2);async function call(path,body){const r=await fetch('/api/datasets/'+encodeURIComponent(el('dataset').value)+'/'+path,{method:body?'POST':'GET',headers:{authorization:'Bearer '+el('token').value,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const value=await r.json();if(!r.ok)throw new Error(value.error||r.status);return value;}el('read').onclick=async()=>{try{state=(await call('read')).state;show(state);}catch(e){state=null;show({error:e.message});}};el('command').onclick=async()=>{try{if(!state)throw new Error('Hãy đọc trạng thái trước.');if(state.dataset_id!==el('dataset').value)throw new Error('Dataset thay đổi, hãy đọc lại.');const action=el('action').value,value=el('value').value;const body={command_id:crypto.randomUUID(),expected_control_revision:state.control_revision,expires_at:new Date(Date.now()+60000).toISOString(),action,reason:el('reason').value};if(action==='FREEZE'){if(!['true','false'].includes(value))throw new Error('Giá trị phải là true hoặc false.');body.frozen=value==='true';}if(action==='TRANSFER')body.owner=value;if(action==='RESTRICT_AT')body.effective_from=value;el('command').disabled=true;const result=await call('control',body);state=result.state;show(result);}catch(e){state=null;show({error:e.message});}finally{el('command').disabled=false;}};`;
const style=`body{font:16px system-ui;background:#f5f7fa;color:#172337;margin:0}main{max-width:720px;margin:40px auto;padding:24px}label{display:block;margin:16px 0}input,select{display:block;width:100%;box-sizing:border-box;padding:10px;margin-top:6px}button{padding:10px 16px;margin-right:8px;cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:white;padding:16px}`;
export default {
  async fetch(request,env) {
    const headers={'cache-control':'no-store','content-security-policy':"default-src 'none'; script-src 'self'; style-src 'self'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'",'x-content-type-options':'nosniff','referrer-policy':'no-referrer'};
    try {
      requireThat(env.ENVIRONMENT_ID==='local-test'||env.ENVIRONMENT_ID==='isolated-test','OPERATOR_ENVIRONMENT_BLOCKED',503);
      const u=new URL(request.url);
      if(request.method==='GET' && ['/','/console.js','/style.css'].includes(u.pathname))return new Response(u.pathname==='/'?page:u.pathname==='/console.js'?script:style,{headers:{...headers,'content-type':u.pathname==='/'?'text/html; charset=utf-8':u.pathname==='/console.js'?'text/javascript; charset=utf-8':'text/css; charset=utf-8'}});
      const match=/^\/api\/datasets\/([a-zA-Z0-9._-]+)\/(read|control)$/.exec(u.pathname);requireThat(match,'NOT_FOUND',404);
      requireThat((match[2]==='read'&&request.method==='GET')||(match[2]==='control'&&request.method==='POST'),'METHOD_DENIED',405);
      const auth=request.headers.get('authorization');requireThat(auth?.startsWith('Bearer '),'AUTH_DENIED',401);
      const body=request.method==='POST'?await request.text():undefined;requireThat(!body||new TextEncoder().encode(body).length<=16384,'COMMAND_TOO_LARGE',413);
      const response=await env.CORE_COMMAND.fetch('https://core/datasets/'+match[1]+'/'+match[2],{method:request.method,headers:{authorization:auth,'content-type':'application/json'},...(body?{body}:{})});
      return new Response(response.body,{status:response.status,headers:{...headers,'content-type':'application/json'}});
    }catch(e){return Response.json({error:e instanceof ContractError?e.code:'OPERATOR_UNAVAILABLE'},{status:e instanceof ContractError?e.status:503,headers});}
  }
};
