import {readFile,writeFile} from 'node:fs/promises';import {spawnSync} from 'node:child_process';import {randomBytes,randomUUID} from 'node:crypto';
import {hash,requireThat,ContractError} from '../../src/platform/contracts.js';import {progressFixtureConfig} from '../../src/preparation/progress-config.js';
import {principalSecrets} from './prepare.js';import {waitForCapabilityStatus} from './capability-readiness.js';import {S3ReadonlyReader} from '../../src/platform/s3-reader.js';import {verifyAttestation} from '../../src/platform/receipts.js';import {buildBackup} from '../../src/preparation/recovery.js';import {savePortableBackup,loadPortableBackup} from '../preparation/portable-backup.js';
const iso=ms=>new Date(ms).toISOString(),mode=process.argv[2],root='.cloud-proof/';
let proof,plan,report={status:'CLOUD_PROGRESS_NOT_RUN',g1:'NOT_PASSED',production_enabled:false,legacy_sources_read:false,cases:[]};
const save=()=>writeFile(root+'progress-evidence.json',JSON.stringify(report,null,2)+'\n');
const check=async(name,fn)=>{try{await fn();report.cases.push({name,status:'PASS'});}catch(e){report.cases.push({name,status:'FAIL',error:e instanceof ContractError?e.code:'PROGRESS_PROOF_FAILED'});throw e;}finally{await save();}};
const core=async(path,body,token)=>{const r=await fetch(proof.origins.core+'/datasets/'+proof.trust.dataset_id+'/'+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},redirect:'error',signal:AbortSignal.timeout(15000),...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json()};};
const progress=async(path,body,token=plan.scheduler_token)=>{const r=await fetch(plan.origin+path,{method:body===undefined?'GET':'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},redirect:'error',signal:AbortSignal.timeout(15000),...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,body:await r.json()};};
const command=(args)=>{const r=spawnSync('node_modules/.bin/wrangler',args,{stdio:'pipe',encoding:'utf8',env:{...process.env,CLOUDFLARE_API_TOKEN:process.env.CF_TEST_API_TOKEN,CLOUDFLARE_ACCOUNT_ID:proof.trust.account_id,WRANGLER_SEND_METRICS:'false'}});requireThat(r.status===0,'PROGRESS_CLEANUP_COMMAND_FAILED',503);};
try{
 proof=JSON.parse(await readFile(root+'proof.private.json','utf8'));
 if(mode==='prepare'){
  const f=await progressFixtureConfig(proof.trust.account_id,proof.trust.dataset_id,iso(Date.now()));const token=randomBytes(32).toString('hex');if(process.env.GITHUB_ACTIONS==='true')console.log('::add-mask::'+token);
  plan={scheduler_token:token,config:f.config,config_hash:f.config_hash,origin:'https://'+f.worker.name+'.openpq-intelligence.workers.dev'};
  await writeFile(root+'progress.json',JSON.stringify(f.worker));await writeFile(root+'progress.private.json',JSON.stringify(plan),{mode:0o600});
  await writeFile(root+'progress-secrets.json',JSON.stringify({PROGRESS_CONFIG_JSON:JSON.stringify(f.config),PROGRESS_CONFIG_HASH:f.config_hash,SCHEDULER_TOKEN_HASH:await hash(token),EXPORT_ONLY_TOKEN:proof.tokens.exporter}),{mode:0o600});
  report={...report,code_sha:process.env.GITHUB_SHA,run_id:process.env.GITHUB_RUN_ID,run_attempt:process.env.GITHUB_RUN_ATTEMPT,account_id:proof.trust.account_id,dataset_id:proof.trust.dataset_id,config:f.config,config_hash:f.config_hash,status:'CLOUD_PROGRESS_PREPARED'};await save();
 }else{
  plan=JSON.parse(await readFile(root+'progress.private.json','utf8'));report=JSON.parse(await readFile(root+'progress-evidence.json','utf8'));
  if(mode==='prove'){
   await check('actual final Core probe is absent and fresh fixture bootstrap is locator pinned',async()=>{
    await waitForCapabilityStatus(()=>fetch(proof.origins.core+'/probe',{redirect:'error',signal:AbortSignal.timeout(15000)}),404,{failureCode:'PROGRESS_CORE_PROBE_REMOVAL_NOT_OBSERVED',observe:value=>report.probe_observation=value});
    const b={...proof.trust,owner:'proof-owner',epoch:1};requireThat((await core('bootstrap',b,proof.tokens.operator)).status===200,'PROGRESS_BOOTSTRAP_FAILED');requireThat((await core('bootstrap',b,proof.tokens.operator)).status===409,'PROGRESS_BOOTSTRAP_NOT_SINGLE_USE');
   });
   const state=async()=>{const r=await core('read',undefined,proof.tokens.read);requireThat(r.status===200,'PROGRESS_CORE_READ_FAILED');return r.body.state;};
   await check('actual scheduler capability cannot read, control, prepare or commit publication',async()=>{for(const path of ['read','control','prepare','commit']){const r=await core(path,path==='read'?undefined:{},proof.tokens.exporter);requireThat(r.status===403,'EXPORT_ONLY_CAPABILITY_ESCAPE');}});
   await check('actual scheduler rejects unauthenticated, wrong dataset and non-export jobs',async()=>{const j={id:'wrong',kind:'EXPORT_CHECKPOINT',dataset_id:proof.trust.dataset_id,expires_at:iso(Date.now()+60000)};requireThat((await progress('/enqueue',j,'invalid')).status===401,'PROGRESS_UNAUTHENTICATED_ALLOWED');for(const body of [{...j,kind:'PROMOTE'},{...j,dataset_id:'real-dataset'}])requireThat((await progress('/enqueue',body)).body.error==='PROGRESS_TASK_DENIED','PROGRESS_TASK_ESCAPE');});
   const before=await state(),now=Date.now();const c={schema_version:'openpq-candidate-v1',...proof.trust,candidate_id:randomUUID(),expected_revision:before.revision,expected_control_revision:before.control_revision,logical_slot:before.revision+20,evaluation_time:iso(now),valid_from:iso(now-1000),valid_to:iso(now+600000),inputs:[{source_id:'synthetic-progress-fixture',source_type:'MANUAL',source_time:iso(now-1000),valid_to:iso(now+600000),max_age_ms:600000}],quality:{completeness:'COMPLETE',resolution:'RESOLVED'},artifacts:proof.trust.artifacts,payload:{fixture_only:true,not_a_real_operational_status:true},operation:'NORMAL',decision:{type:'cano.operation.fixture',kind:'FACT',effect:'ABSTAIN',action_until:iso(now+600000),minimum_evidence_met:false,reason_codes:['SYNTHETIC_PROGRESS_NO_ACTION']}};
   const prepared=await core('prepare',c,proof.tokens.live);report.publication_prepare_observation={status:prepared.status,error:typeof prepared.body.error==='string'&&/^[A-Z0-9_]{1,80}$/.test(prepared.body.error)?prepared.body.error:null};requireThat(prepared.status===200,'PROGRESS_FIXTURE_PREPARE_FAILED');const committed=await core('commit',{...proof.trust,command_id:randomUUID(),digest:prepared.body.digest,expires_at:iso(Date.now()+60000)},proof.tokens.live);requireThat(committed.status===200,'PROGRESS_FIXTURE_COMMIT_FAILED');
   const active=await state(),job={id:randomUUID(),kind:'EXPORT_CHECKPOINT',dataset_id:proof.trust.dataset_id,expires_at:iso(Date.now()+180000)};
   await check('actual cloud DO alarm drains committed outbox with idempotent scoped job',async()=>{
    requireThat((await progress('/enqueue',job)).body.created===true,'PROGRESS_ENQUEUE_FAILED');requireThat((await progress('/enqueue',job)).body.created===false,'PROGRESS_JOB_DUPLICATED');let observed;
    await waitForCapabilityStatus(async()=>{const r=await progress('/status');observed=r.body;return {status:r.status===200&&r.body.jobs?.find(x=>x.id===job.id)?.state==='DONE'?200:503};},200,{failureCode:'CLOUD_PROGRESS_ALARM_NOT_OBSERVED',observe:value=>report.alarm_observation=value});
    report.scheduler_status=observed;requireThat(await hash(await state())===await hash(active),'SCHEDULER_CHANGED_AUTHORITY');requireThat((await core('export',{},proof.tokens.operator)).body.exported.length===0,'SCHEDULER_OUTBOX_NOT_DRAINED');
   });
   const reader=new S3ReadonlyReader(JSON.parse((await readFile(root+'runtime-secrets.json','utf8'))).S3_READONLY_CONFIG),key=`checkpoints/${proof.trust.authority_instance_id}/${proof.trust.recovery_generation}/latest.json`,envelope=JSON.parse(await reader.get(key));
   await check('signed cloud checkpoint and Runtime match the committed non-actionable fixture',async()=>{const receipt=await verifyAttestation(envelope,proof.trust);requireThat(receipt.revision===committed.body.receipt.revision&&receipt.digest===prepared.body.digest,'PROGRESS_CHECKPOINT_MISMATCH');const response=await fetch(proof.origins.runtime+'/datasets/'+proof.trust.dataset_id,{redirect:'error',signal:AbortSignal.timeout(15000)}),view=await response.json();requireThat(response.status===200&&view.receipt.digest===receipt.digest&&view.serving.authority==='VERIFIED'&&view.serving.decision_eligibility==='ABSTAIN','PROGRESS_RUNTIME_MISMATCH');report.receipt=receipt;});
   await check('actual cloud publication exports to portable backup and reopens with independent trust',async()=>{
    const generation=JSON.parse(await reader.get(envelope.receipt.key));const bundle=await buildBackup({environment_id:'isolated-test',authority:proof.trust,created_at:iso(Date.now()),watermark:{revision:active.revision,control_revision:active.control_revision},required_keys:['control','receipt',envelope.receipt.key],records:[{key:'control',kind:'CONTROL',content:active},{key:'receipt',kind:'RECEIPT',content:envelope},{key:envelope.receipt.key,kind:'GENERATION',content:generation},...['AUDIT','REGISTRY','SCHEDULER','DEPLOY'].map(kind=>({key:kind.toLowerCase(),kind,content:kind==='SCHEDULER'?{fixture_only:true,config:plan.config}:kind==='DEPLOY'?{fixture_only:true,code_sha:process.env.GITHUB_SHA}:{synthetic_fixture:true,full_authoritative_export:false}}))]});
    report.backup=await savePortableBackup(bundle,proof.trust,root+'portable-publication-backup');report.backup_readback=(await loadPortableBackup(root+'portable-publication-backup',proof.trust)).verification;report.full_system_backup_proven=false;
   });report.status='CLOUD_PROGRESS_SUBSET_PASS';await save();
  }else if(mode==='cleanup'){
   await check('temporary scheduler and Core export capability closure actually observed',async()=>{
    for(const name of ['SCHEDULER_TOKEN_HASH','EXPORT_ONLY_TOKEN'])command(['secret','delete',name,'--config',root+'progress.json']);command(['deploy','--config',root+'progress.json']);
    const secrets=JSON.parse(await readFile(root+'core-secrets.json','utf8'));const principals=['PRINCIPALS_JSON','PRINCIPALS_JSON_2','PRINCIPALS_JSON_3'].flatMap(k=>JSON.parse(secrets[k]||'[]')).filter(x=>x.token!==proof.tokens.exporter);await writeFile(root+'export-close.private.json',JSON.stringify(principalSecrets(principals)),{mode:0o600});command(['secret','bulk',root+'export-close.private.json','--config',root+'core.json']);command(['deploy','--config',root+'core.json']);
    await waitForCapabilityStatus(()=>core('export',{},proof.tokens.exporter),401,{failureCode:'PROGRESS_EXPORT_REVOKE_NOT_OBSERVED',observe:value=>report.export_revoke_observation=value});
    await waitForCapabilityStatus(async()=>{const r=await progress('/status');return {status:r.status===503&&r.body.error==='PROGRESS_CAPABILITY_MISSING'?503:200};},503,{failureCode:'PROGRESS_SCHEDULER_CLOSURE_NOT_OBSERVED',observe:value=>report.scheduler_closure_observation=value});
    const witness=await fetch(proof.origins.runtime+'/datasets/'+proof.trust.dataset_id,{redirect:'error',signal:AbortSignal.timeout(15000)});const body=await witness.json();requireThat(witness.status===200&&(!report.receipt||body.receipt?.digest===report.receipt.digest),'PROGRESS_CLEANUP_WITNESS_FAILED');report.cleanup='SUCCESS';
   });await save();
  }else throw new ContractError('PROGRESS_MODE_INVALID');
 }
}catch(error){report.status='CLOUD_PROGRESS_BLOCKED_OR_FAILED';report.error=error instanceof ContractError?error.code:'PROGRESS_PROOF_FAILED';await save();console.error(report.error);process.exitCode=1;}
